name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: https://gitea.com/actions/checkout@v4

      - name: Create .env
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Deploy
        run: |
          docker compose up -d --build