name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Pull and Build containers
        run: |
          cd /home/user/Documents/projects/file-vault
          git pull
          docker compose up -d --build