services:
  api-gateway:
    build:
      context: api-gateway
      dockerfile: ./Dockerfile
    container_name: file-vault_api-api-gateway
    ports:
      - "${API_GATEWAY_PORT}:5000"
    env_file:
      - .env
    volumes:
      - ./shared:/shared
    depends_on:
      file-service:
        condition: service_healthy


  file-service:
    build:
      context: ./file-service
      dockerfile: ./Dockerfile
    container_name: file-vault_file-service
    ports:
      - "${FILE_SERVICE_PORT}:50051"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    healthcheck:
      test: [ "CMD-SHELL", "nc -z localhost 50051" ]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:18-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: "${POSTGRES_USERNAME}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DATABASE}"
    ports:
      - "${POSTGRES_PORT_EXTERNAL}:${POSTGRES_PORT_INTERNAL}"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USERNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    container_name: minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: "${MINIO_USER}"
      MINIO_ROOT_PASSWORD: "${MINIO_PASSWORD}"
    ports:
      - "9001:9001"   # Web UI
    volumes:
      - minio_data:/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  minio_data:
